image: node:12.18.2-buster
stages:
  - deploy

variables:
  image_name: "pi-site"
  service_name: "pi-site"
  project_url: "https://gitlab.bscox.com/cox5529/pi-site.git"
  docker_directory: "."

deploy:
  stage: deploy
  script:
    - which ssh-agent || (apt-get update -y && apt-get install expect openssh-client -y)
    - eval $(ssh-agent -s)
    - echo "$deploy_key" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no gitlab@10.0.0.33 "sh deploy.sh $project_url $image_name frontend $service_name $docker_directory"
