version: '3.3'
services:
  nginx:
    image: registry.bscox.com/cox5529/pi-site:latest
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24