version: '3.3'
services:
  nginx:
    image: registry.bscox.com/cox5529/pi-site:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /etc/certs
        target: /etc/certs

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.0.1.0/24
