version: '3.3'
services:
  nginx:
    image: registry.bscox.com/cox5529/pi-site:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /etc/certs
        target: /etc/certs
    networks:
      - default
networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 172.0.1.0/24
